### ISSUE TITLE
Lester's TODO list

### ISSUE THREAD

**Issue by lohedges** [michellab/BioSimSpace#128]
Just a check list of known issues and things TODO before I go on leave:

* [ ] 1) Finish JOSS submission process. Review thread is [here](https://github.com/openjournals/joss-reviews/issues/1831).

* [x] 2) Document versions of external tools that BioSimSpace supports. Probably hard to be comprehensive, but can at least document versions that we've tested against, e.g. GROMACS > 5.0, AmberTools18/AmbertTools19, etc.

* [ ] 3) Updated `BioSimSpace.Process.Amber` to add support for AMBER simulations using `pmemd` and `pmemd.cuda`. Currently we only support `sander`. (`pmemd` and `pmemd.cuda` are searched for when using the `BioSimSpace.MD.run` function.)

* [ ] 4) Handle execution of MD processes using `mpirun`. Probably need to detect the presence of a hostfile. Will likely need to support `mpirun`, `mpiexec`, and `srun`. (Note that `srun` doesn't require a hostfile, so there might not be a single solution.)

* [x] 5) Make error messages more informative for some of the common exceptions that are trigged. It could be best to add a _verbose_ mode that prints the full Sire error if activated.

* [ ] 6) Work out how to capture errors within a node. I think we might need something like `node.addProcess`, which will zip up the working directory of a process if it fails and present this to the user, e.g.

```python
# Generate an MD process to run the protocol.
process = BSS.MD.run(system, protocol)

# Add the process to the node so that error output can be captured.
# Could be tricky if the user overwrites the process within the same node.
node.addProcess(process)
```

* [x] 7) Add documentation explaining how to modify a protocol. This is a little tricky since protocols aren't defined in isolation and can require information from multiple objects, e.g. the `System` and the `Process`. It should be possible to explain the basic concepts though. Perhaps it is easiest for the user to override the `_generate_config` methods of each process to customise the protocols.

**Comment by jmichel80** [comment]
0. Finish the JOSS submission process should stay on top of the to-do list. 
1.  Yes important.
2. Yes we should run pmemd.cuda by default on GPU instances for plain MD (if available). 
3. Sounds tricky to make it work reliably and test thoroughly in a short amount of time?
4. If you list the exceptions you have in mind we can discuss what a useful error message would look like for each of those instances.  
5. Sounds useful but I worry it's harder than it looks and therefore not doable within the time left. 
6. That's important, we should aim to describe well the process to implement the currently implemented different protocols (MD or free energy or metadynamics...) so the doc can be used as a roadmap for future protocols. I would do that rather than refactor code to make the job easier for the user.

**Comment by lohedges** [comment]
I've reverted the original formatting in my first post since it was specific markdown so I could check items off as they are completed. I've added your numbering _after_ the square brackets instead.

Thanks for the comments. This is also list of known limitations as well as things to do, just so whoever is maintaining things is aware of them in my absence.

With regards to the JOSS submission: Since the review process is now active, there's not much I can do until the reviews are in. This _should_ be done within two weeks (hopefully sooner) so these were to keep me occupied in the mean time.

For 5), I've now implemented a _verbose_ mode that prints the full exception trace if activated. This can be done using `BSS.setVerbose(True)` if working interactive or in a script, or using `--verbose` when running a node from the command-line. This just prints the full traceback, which is mostly the output of whatever Sire exception was triggered. I'll push this to `devel` later when I have tested it fully. I'll also try to group some common exceptions and post them here. (Most are IO errors). I feel like I've already done a pretty good job of catching errors that occur during merging, or when copying properties from a parameterised molecule back into the molecule that was originally passed in.
